/**
 * Copyrigt (2020, ) Institute of Software, Chinese Academy of Sciences
 */
package test.test.services;

import org.springframework.beans.factory.annotation.Autowired;
import test.test.mappers.UserMapper;
import test.test.models.User;
import com.github.tools.annotations.api.FunctionDescriber;
import com.github.webfrk.core.HttpBodyHandler;
import com.github.tools.annotations.ServiceDefinition;
import javax.validation.*;
import javax.validation.constraints.*;
import com.github.tools.annotations.api.Required;

/**
 * This code is auto-generated by <code>ServiceGenerator<code>
 *
 */
@ServiceDefinition
public class UserService extends HttpBodyHandler {

	@Autowired
	private UserMapper userMapper;

	@FunctionDescriber(shortName = "创建用户", description = "暂无", prerequisite = "暂无")
	public void addUser(@Valid User user) {
		 userMapper.addUser(user);
	}

	@FunctionDescriber(shortName = "根据name查询用户", description = "暂无", prerequisite = "暂无")
	public test.test.models.User getUser(@Required(true) @Size(min = 10, max = 20) String name) {
		return userMapper.getUser(name);
	}

}